# Generated by Django 3.2.4 on 2021-06-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='start_date',
        ),
    ]
