# Generated by Django 3.2.4 on 2021-06-13 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210611_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='task',
            new_name='task_name',
        ),
        migrations.AddField(
            model_name='user_data',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_data',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
